# Generated by Django 3.1 on 2020-10-16 18:22

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(default='mcs.mathcrib@gmail.com', max_length=254, verbose_name='От кого')),
                ('subject', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('html_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('to_emails', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
        ),
    ]
