# Generated by Django 3.1 on 2020-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200915_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(max_length=100, unique=True, verbose_name='Телеграм аккаунт'),
        ),
    ]
