# Generated by Django 3.1 on 2020-08-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200812_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('автор', 'Author'), ('модератор', 'Moderator')], default='автор', max_length=50, verbose_name='Роль'),
        ),
    ]
