# Generated by Django 3.1 on 2020-08-21 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200812_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата приглашения')),
                ('key', models.CharField(max_length=50, verbose_name='Ключ')),
                ('invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный')),
                ('inviting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviting', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
            ],
        ),
    ]
