# Generated by Django 3.1 on 2020-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_inviteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteduser',
            name='key',
        ),
        migrations.AddField(
            model_name='inviteduser',
            name='invite_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка для регистрации'),
        ),
    ]
