# Generated by Django 3.1 on 2020-08-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_inviteduser_invite_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteduser',
            options={'ordering': ['-created'], 'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
    ]
