# Generated by Django 2.2 on 2020-08-09 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200809_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Cтатьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
    ]
