# Generated by Django 2.2 on 2020-08-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200809_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'cтатья', 'verbose_name_plural': 'cтатьи'},
        ),
    ]
