# Generated by Django 3.1 on 2020-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200812_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
