# Generated by Django 3.1 on 2020-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
