# Generated by Django 3.1 on 2020-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.BooleanField(default=False, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время чтения'),
        ),
    ]
