# Generated by Django 3.1 on 2020-08-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200815_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='is_category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='is_published',
        ),
    ]
