# Generated by Django 3.1 on 2020-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200815_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время чтения статьи'),
        ),
    ]
