# Generated by Django 3.1 on 2020-08-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200825_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время чтения статьи'),
        ),
    ]
