# Generated by Django 3.1 on 2020-08-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200825_1714'),
        ('articles', '0012_auto_20200821_1952'),
    ]

    operations = [
    ]
