# Generated by Django 3.1 on 2020-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_merge_20200826_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время чтения статьи'),
        ),
    ]
